name: weather_admin
description: Weather Admin
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  cloud_functions: ^4.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
